spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mariadb://localhost:3306/undong_minjok?serverTimezone=Asia/Seoul
    username: undong
    password: minjok
    hikari:
      maximum-pool-size: 10        # ?? ??? ??
      minimum-idle: 5              # ?? ?? ??? ?
      idle-timeout: 30000          # idle ??? ?? ??(ms)
      max-lifetime: 1800000        # ???? ?? ??(ms) - ?? 30?
      connection-timeout: 30000    # ??? ??? ??? ??? ? ?? ?? ??(ms)

  jpa:
    hibernate:
      ddl-auto: update    # create, create-drop, update, validate, none ? ??
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false            # ??? ?? ??

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
        transport:
          protocol: smtp
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret-key: Q8b83bmIq4KI2lvE+bViXYvo9SyODg1g0Q0dPyG9VNutj0GgBG8SxhWwL3oexDlWtq5uxFZs+k+NWXHYXKLjYg==
  expiration: 3600000  # 1시간
  refresh-expiration: 1209600000 # 2주

server:
  port: 8888                      # ?? ??

file:
  root-dir: ./uploads

toss:
  payments:
    secret-key: ${TOSS-SECRET-KEY}
    client-key: ${TOSS-CLIENT-KEY}
    base-url: ${TOSS-BASE-URL}
    success-url: ${TOSS-SUCCESS-KEY-LOCAL}
    fail-url: ${TOSS-FAIL-KEY-LOCAL}