spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/undong
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10        # ?? ??? ??
      minimum-idle: 5              # ?? ?? ??? ?
      idle-timeout: 30000          # idle ??? ?? ??(ms)
      max-lifetime: 1800000        # ???? ?? ??(ms) - ?? 30?
      connection-timeout: 30000    # ??? ??? ??? ??? ? ?? ?? ??(ms)

  jpa:
    hibernate:
      ddl-auto: update    # create, create-drop, update, validate, none ? ??
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false            # ??? ?? ??

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
        transport:
          protocol: smtp
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration: 3600000  # 1시간
  refresh-expiration: 1209600000 # 2주

server:
  port: 8888                      # ?? ??

file:
  root-dir: /app/uploads

logging:
  level:
    root: INFO
  file:
    path: /app/logs

toss:
  payments:
    secret-key: ${TOSS-SECRET-KEY}
    client-key: ${TOSS-CLIENT-KEY}
    base-url: ${TOSS-BASE-URL}
    success-url: ${TOSS-SUCCESS-KEY-DEV}
    fail-url: ${TOSS-FAIL-KEY-DEV}